config/routes.rb
Rails.application.routes.draw do

  devise_for :creatrixes

  get 'digitales_dot_gg/homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'tales#index'

  resources :tales do
  	resources :what_ifs
  	resources :m_statements
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creatrix.rb
class Creatrix < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tales
end

app/models/m_statement.rb
class MStatement < ApplicationRecord
	belongs_to :tale
end

app/models/tale.rb
class Tale < ApplicationRecord
	belongs_to :creatrix
	has_many :what_ifs
	has_many :m_statements

	has_many :what_ifs

	validates :title, presence: true
end

app/models/what_if.rb
class WhatIf < ApplicationRecord
	belongs_to :tale
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/digitales_dot_gg_controller.rb
class DigitalesDotGgController < ApplicationController
  def homepage
  end
end

app/controllers/m_statements_controller.rb
class MStatementsController < ApplicationController
	def index
		@tale = Tale.find(params['tale_id'])
		@m_statements = @tale.m_statements
	end

	def new
		@m_statement = MStatement.new
	end

	def create
		@tale = Tale.find(params['tale_id'])
		hash = params['m_statement']

		@m_statement = MStatement.create(tale: @tale, title: hash['title'], description: hash['description'])

		redirect_to tale_m_statements_path(@tale.id)
	end

	def edit
		@tale = Tale.find(params['tale_id'])
		@m_statement = MStatement.find(params['id'])
	end

	def update
		@tale = Tale.find(params['tale_id'])
		@m_statement = MStatement.find(params['id'])

		hash = params['m_statement']

		@m_statement.update(title: hash['title'], description: hash['description'])

		redirect_to tale_m_statements_path(@tale.id)
	end
end

app/controllers/tales_controller.rb
class TalesController < ApplicationController
  before_action :authenticate_creatrix!
  
  def index
  end

  def show
  end

  def new
    @tale = Tale.new
  end

  def create
    hash = params['tale']
    @tale = Tale.create(creatrix: current_creatrix, title: hash['title'], description: hash['description'])

    redirect_to tales_path
  end

  def edit
    @tale = Tale.find(params['id'])
  end

  def update
    @tale = Tale.find(params['id'])
    hash = params['tale']
    @tale.update(title: hash['title'], description: hash['description'])

    redirect_to tales_path
  end
end

app/controllers/what_ifs_controller.rb
class WhatIfsController < ApplicationController
  def index
    @tale = Tale.find(params['tale_id'])
    @what_ifs = @tale.what_ifs
  end

  def show
  end

  def new
    @tale = Tale.find(params['tale_id'])

    @what_if = WhatIf.new
  end

  def create
    @tale = Tale.find(params['tale_id'])
    hash = params['what_if']

    @what_if = WhatIf.create(tale: @tale, title: hash['title'], description: hash['description'])

    redirect_to tale_what_ifs_path(@tale.id)
  end

  def edit
    @tale = Tale.find(params['tale_id'])
    @what_if = WhatIf.find(params['id'])
  end

  def update
    @tale = Tale.find(params['tale_id'])
    @what_if = WhatIf.find(params['id'])

    hash = params['what_if']

    @what_if.update(title: hash['title'], description: hash['description'])

    redirect_to tale_what_ifs_path(@tale.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/digitales_dot_gg_helper.rb
module DigitalesDotGgHelper
end

app/helpers/m_statements_helper.rb
module MStatementsHelper
end

app/helpers/tales_helper.rb
module TalesHelper
end

app/helpers/what_ifs_helper.rb
module WhatIfsHelper
end

app/views/digitales_dot_gg/homepage.html.erb
<h1>DigitalesDotGg#homepage</h1>
<p>Find me in app/views/digitales_dot_gg/homepage.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalesV1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/m_statements/edit.html.erb
<h1>edit core m statement</h1>

<%= form_for @m_statement, url: {action: "update"} do |f| %>
	<%= label_tag(:title, "title") %><br />
	<%= f.text_field :title, placeholder: @m_statement.title %><br />
	<%= label_tag(:description, "description") %><br />
	<%= f.text_field :description, size: "60x12", placeholder: @m_statement.description %><br />
	<%= f.submit "edit" %>
<% end %>

app/views/m_statements/index.html.erb
<h1><%= @tale.title %>'s m core m_statements</h1>

<% @m_statements.each do |m_statement| %>
	<p>might or might not - <%= m_statement.title + ' ||| ' + m_statement.description %></p>
	<p><%= link_to 'edit', edit_tale_m_statement_path(@tale.id, m_statement.id) %></p><br />
	<p>see settings</p><br /><br /><hr />
<% end %>

<% if @tale.m_statements.count < 7 %>
	<br />

	<p><%= link_to "add a new m statement", new_tale_m_statement_path(@tale.id) %></p>
<% end %> 

<br />

<p><%= link_to 'back', tale_what_ifs_path(@tale.id) %></p>

app/views/m_statements/new.html.erb
<h1>create a new core m statement</h1>


<%= form_for @m_statement, url: {action: "create"} do |f| %>
	<%= label_tag(:title, "title") %><br />
	<%= f.text_field :title %><br />
	<%= label_tag(:description, "description") %><br />
	<%= f.text_field :description %><br />
	<%= f.submit "create" %>
<% end %>

app/views/tales/edit.html.erb
<h1>edit</h1>

<%= form_for @tale, url: {action: "update"} do |f| %>
	<%= label_tag(:title, "title") %><br />
	<%= f.text_field :title, placeholder: @tale.title %><br />
	<%= label_tag(:description, "description") %><br />
	<%= f.text_field :description, size: "60x12", placeholder: @tale.description %><br />
	<%= f.submit "edit" %>
<% end %>

app/views/tales/index.html.erb
<h1>tales</h1>

<% current_creatrix.tales.each do |tale|%>
	<p>title : <%= tale.title %></p>
	<p>first statement : <%= tale.description %></p>
	<p><%= link_to 'edit', edit_tale_path(tale.id) %></p><br /><br />
	<p>
		<%= link_to 'see what ifs', tale_what_ifs_path(tale.id)%><br />
		<%= link_to 'see m_statements', tale_m_statements_path(tale.id) %><br />
		see settings<br />
		see chron storylines<br />
		see achron storylines of storytelling digits
	</p><br />
	<hr />
<% end %>

<p><%= link_to 'create a new tale', new_tale_path %></p>

app/views/tales/new.html.erb
<h1>create</h1>


<%= form_for @tale, url: {action: "create"} do |f| %>
	<%= label_tag(:title, "title") %><br />
	<%= f.text_field :title %><br />
	<%= label_tag(:description, "first statement") %><br />
	<%= f.text_field :description %><br />
	<%= f.submit "create" %>
<% end %>

app/views/what_ifs/edit.html.erb
<h1>edit 'What if... ?' proposition</h1>

<%= form_for @what_if, url: {action: "update"} do |f| %>
	<%= label_tag(:title, "title") %><br />
	<%= f.text_field :title, placeholder: @what_if.title %><br />
	<%= label_tag(:description, "description") %><br />
	<%= f.text_field :description, size: "60x12", placeholder: @what_if.description %><br />
	<%= f.submit "edit" %>
<% end %>

app/views/what_ifs/index.html.erb
<h1><%= @tale.title %>'s 'What if... ?' propositions</h1>

<% @what_ifs.each do |what_if| %>
	<p>what if - <%= what_if.title %></p>
	<p><%= link_to 'edit', edit_tale_what_if_path(@tale.id, what_if.id) %></p><br />
<% end %>

<% if @tale.what_ifs.count < 3 %>
	<br />

	<p><%= link_to "add a new 'What if... ?' proposition", new_tale_what_if_path(@tale.id) %></p>
<% end %> 

<br />

<p><%= link_to 'see m statements', tale_m_statements_path(@tale.id) %></p><br />

<p><%= link_to 'back', tales_path %></p>

app/views/what_ifs/new.html.erb
<h1>create a new 'What if... ?' proposition</h1>


<%= form_for @what_if, url: {action: "create"} do |f| %>
	<%= label_tag(:title, "title") %><br />
	<%= f.text_field :title %><br />
	<%= label_tag(:description, "description") %><br />
	<%= f.text_field :description %><br />
	<%= f.submit "create" %>
<% end %>